apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.Name }}-storage-claim"
  namespace: {{ .Values.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.pvcStorage }}
